name: Deploy to aws cloud

on:
  push:
    branches: ['terraform']

jobs:

  terraform:
    name: Terraform Validation and Build
    runs-on: ubuntu-latest
    env:
      TF_VAR_ECR_REPOSITORY_NAME: ${{ github.repository }}
      TF_VAR_LAMBDA_DOCKER_IMAGE: UNSET
      DOCKER_IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}

    steps:
      - uses: actions/checkout@v2.5.0

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform init, plan
        run: |
          cd terraform

          echo "** Running Terraform Init**"
          terraform init

          echo "** Running Terraform Plan**"
          terraform plan

      - name: Terraform ecr repository
        run: |
          cd terraform

          echo "** Running Terraform Apply**"
          terraform apply -target=module.ecr

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Build, tag, and push docker image to Amazon ECR Public
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REPOSITORY: ${{ github.repository }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$DOCKER_IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$DOCKER_IMAGE_TAG

      - name: Terraform init, plan and apply
        env:
          TF_VAR_LAMBDA_DOCKER_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:$DOCKER_IMAGE_TAG
        run: |
          cd terraform

          echo "** Running Terraform Apply**"
          terraform apply -auto-approve