name: Deploy to aws cloud

on:
  push:
    branches: ['terraform']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  terraform:
    name: Terraform Validation and Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.5.0

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform init, plan and apply
        run: |
          cd terraform

          echo "** Running Terraform Init**"
          terraform init
          
          echo "** Running Terraform Validate**"
          terraform validate
          
          echo "** Running Terraform Plan**"
          terraform plan

          echo "** Running Terraform Apply**"
          terraform apply -auto-approve